candidate_terms = [
    # Terms related to code in general
    "function",
    "method",
    "variable",
    "class",
    "object",
    "type",
    "setup",
    "initialize",
    "loop",
    "procedure",
    #  Terms related to componets an UI
    "component",
    "dialog",
    "form",
    "layout",
    "screen",
    "UI",
    "UX",
    "button",
    "input",
    "label",
    "message",
    "menu",
    # Terms related to configuration and files
    "configuration",
    "config",
    "settings",
    "preferences",
    "file",
    "path",
    "directory",
    "environment",
    "build",
    "script",
    # Terms related to translations and languages
    "translation",
    "locale",
    "language",
    "string",
    "key",
    "message",
    "label",
    "json",
    "localized",
    # Terms related to processes and interactions
    "process",
    "thread",
    "task",
    "operation",
    "execution",
    "batch",
    "schedule",
    "event",
    "trigger",
    "action",
    # Terms related to tools and libraries
    "adb",
    "scrcpy",
    "gnirehtet",
    "plugin",
    "library",
    "framework",
    "tool",
    "dependency",
    "module",
    "package",
    # Terms related to networks and connections
    "network",
    "connection",
    "wireless",
    "pairing",
    "IP",
    "IPv6",
    "address",
    "QR code",
    "scan",
    "data",
    # Terms related to operating systems and platforms
    "platform",
    "OS",
    "Linux",
    "Windows",
    "Mac",
    "Android",
    "architecture",
    "binary",
    "executable",
    # Terms related to performance and optimization
    "performance",
    "optimization",
    "build",
    "speed",
    "efficiency",
    "memory",
    "CPU",
    "GPU",
    # Terms related to documentation and licenses
    "documentation",
    "license",
    "terms",
    "policy",
    "privacy",
    "README",
    "workflow",
    "manual",
    # Terms related to visual themes
    "theme",
    "style",
    "color",
    "dark mode",
    "light mode",
    "icon",
    "SVG",
    "design",
]
